# Generated by Django 3.0.6 on 2020-05-28 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('watering_interval', models.PositiveIntegerField(help_text='In seconds')),
                ('fertilizing_interval', models.PositiveIntegerField(help_text='In seconds')),
                ('required_exposure', models.CharField(choices=[('dark', 'Dark'), ('shade', 'Shade'), ('partsun', 'Part sun'), ('fullsun', 'Full sun')], help_text='Amount of sun', max_length=16)),
                ('required_humidity', models.CharField(help_text='Optimal humidity', max_length=10)),
                ('required_temperature', models.CharField(help_text='Optimal temperature', max_length=16)),
                ('blooming', models.BooleanField(blank=True, default=False)),
                ('difficulty', models.CharField(choices=[(1, 'Low'), (2, 'Medium-low'), (3, 'Medium'), (4, 'Medium-high'), (5, 'High')], default=1, max_length=16, verbose_name='Cultivation difficulty')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('exposure', models.CharField(choices=[('dark', 'Dark'), ('shade', 'Shade'), ('partsun', 'Part sun'), ('fullsun', 'Full sun')], help_text='Amount of sun', max_length=10)),
                ('humidity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Optimal humidity', max_length=10)),
                ('temperature', models.CharField(choices=[('cold', 'Cold'), ('medium', 'Medium'), ('warm', 'Warm')], help_text='Optimal temperature', max_length=10)),
                ('drafty', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('last_fertilized', models.DateTimeField(blank=True, null=True)),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.Plant', verbose_name='Type of plant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
